In [1]:
# numpy.linalg package for linear algbera

In [2]:
import numpy as np

In [3]:
first_array = np.arange(16).reshape(4,4)
first_array.shape

(4, 4)

In [4]:
first_array.ndim

2

In [5]:
first_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [6]:
first_matrix = np.matrix(first_array)
first_matrix

matrix([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [7]:
first_matrix.shape

(4, 4)

In [8]:
first_matrix.ndim

2

In [9]:
second_matrix = np.matrix(np.identity(4))
second_matrix

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [10]:
matrix_a = np.random.randint(5,size=(2,3))
matrix_a

array([[3, 1, 2],
       [0, 3, 0]])

In [11]:
matrix_b = np.random.randint(5,size=(3,2))
matrix_b

array([[2, 1],
       [1, 1],
       [2, 1]])

In [14]:
np.matmul(matrix_a,matrix_b)

array([[11,  6],
       [ 3,  3]])

In [15]:
matrix_c = np.matrix("0 1 2; 1 0 3; 4 -3 8")
matrix_c

matrix([[ 0,  1,  2],
        [ 1,  0,  3],
        [ 4, -3,  8]])

In [16]:
inverse = np.linalg.inv(matrix_c)
inverse

matrix([[-4.5,  7. , -1.5],
        [-2. ,  4. , -1. ],
        [ 1.5, -2. ,  0.5]])

In [17]:
matrix_c * inverse

matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [18]:
np.matmul(matrix_c,inverse)

matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [19]:
A = np.mat("1 -2 1;0 2 -8;-4 5 9")
b = np.array([0,16,-18])

In [20]:
x = np.linalg.solve(A,b)
print(f"Solution: {x}")

Solution: [58. 32.  6.]


In [ ]:
# Matrix decomposition @ matrix factorization - splitting matrix
# prime factorization
# matrix decomposition techniques
    # lower upper decomposition
    # singular value decomposition , decompose into singular vector and value 
    # qr decomposition
    # cholesky factorization
    


In [22]:
first_matrix = np.matrix([
    [4,8],
    [10,14]
])

print(f"Matrix:\n {first_matrix}")

Matrix:
 [[ 4  8]
 [10 14]]


In [23]:
eigenvalues, eigenvectors = np.linalg.eig(first_matrix)
print(eigenvalues)
print(eigenvectors)

[-1.24695077 19.24695077]
[[-0.83619408 -0.46462222]
 [ 0.54843365 -0.885509  ]]


In [24]:
np.linalg.eigvals(first_matrix)

array([-1.24695077, 19.24695077])