In [155]:
import numpy as np

In [156]:
nums = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10]
])

print(nums[0,0],nums[-1,-1])

1 10


In [157]:
multi_arr = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])

In [158]:
multi_arr.ndim

3

In [159]:
multi_arr[1,0,2]

9

In [160]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [161]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [162]:
np.linspace((1,10),(10,20))

array([[ 1.        , 10.        ],
       [ 1.18367347, 10.20408163],
       [ 1.36734694, 10.40816327],
       [ 1.55102041, 10.6122449 ],
       [ 1.73469388, 10.81632653],
       [ 1.91836735, 11.02040816],
       [ 2.10204082, 11.2244898 ],
       [ 2.28571429, 11.42857143],
       [ 2.46938776, 11.63265306],
       [ 2.65306122, 11.83673469],
       [ 2.83673469, 12.04081633],
       [ 3.02040816, 12.24489796],
       [ 3.20408163, 12.44897959],
       [ 3.3877551 , 12.65306122],
       [ 3.57142857, 12.85714286],
       [ 3.75510204, 13.06122449],
       [ 3.93877551, 13.26530612],
       [ 4.12244898, 13.46938776],
       [ 4.30612245, 13.67346939],
       [ 4.48979592, 13.87755102],
       [ 4.67346939, 14.08163265],
       [ 4.85714286, 14.28571429],
       [ 5.04081633, 14.48979592],
       [ 5.2244898 , 14.69387755],
       [ 5.40816327, 14.89795918],
       [ 5.59183673, 15.10204082],
       [ 5.7755102 , 15.30612245],
       [ 5.95918367, 15.51020408],
       [ 6.14285714,

In [163]:
np.full((2,2,2),8).shape


(2, 2, 2)

In [164]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [165]:
np.zeros(5).shape

(5,)

In [166]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [167]:
np.ones((5,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [168]:
a = np.empty(10,dtype=int)
a.fill(12)
print(a)

[12 12 12 12 12 12 12 12 12 12]


In [169]:
np.full(5,10)

array([10, 10, 10, 10, 10])

In [170]:
np.full((5,10),8).shape

(5, 10)

In [171]:
ring_toss = np.array([[1, 0, 0],
                      [0, 0, 1],
                      [1, 0, 1]])

In [172]:
a = np.arange(5)

In [173]:
a

array([0, 1, 2, 3, 4])

In [174]:
a.dtype

dtype('int64')

In [175]:
a.shape

(5,)

In [176]:
m = np.array([np.arange(2),np.arange(2)])
m

array([[0, 1],
       [0, 1]])

In [177]:
m.shape

(2, 2)

In [178]:
n = np.array([
    np.arange(3),
    np.arange(3),
    np.arange(3)
])

n

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [179]:
n.shape

(3, 3)

In [180]:
a = np.array([
    [1,2],
    [3,4]
])

a

array([[1, 2],
       [3, 4]])

In [181]:
print(a[0,0])
print(a[0,1])
print(a[1,0])
print(a[1,1])

1
2
3
4


> $ i \space  \text{is the square root of} -1 $

e.g.  $2.5 + 3.7i$

In [182]:
np.arange(7,dtype='uint16')

array([0, 1, 2, 3, 4, 5, 6], dtype=uint16)

In [183]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [184]:
a

array([[1, 2],
       [3, 4]])

In [185]:
a.dtype.itemsize

8

In [186]:
np.arange(7,dtype='i') # integer

array([0, 1, 2, 3, 4, 5, 6], dtype=int32)

In [187]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [188]:
a[3:7]

array([3, 4, 5, 6])

In [189]:
a[:7:2]

array([0, 2, 4, 6])

In [190]:
a[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1, 0])

In [191]:
b = np.arange(24)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [192]:
b = b.reshape(2,3,4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [193]:
b.shape

(2, 3, 4)

In [194]:
b[0,0,0]

0

In [195]:
b[:,0,0]

array([ 0, 12])

In [196]:
b[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [197]:
b[0,:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [198]:
b[0,...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [199]:
b[0,1]

array([4, 5, 6, 7])

In [200]:
b[0,1,::2]

array([4, 6])

In [201]:
b[...,1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [202]:
b[:,1]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [203]:
b[0,:,1]

array([1, 5, 9])

In [204]:
b[0,:,-1]

array([ 3,  7, 11])

In [205]:
b[0,::-1,-1]

array([11,  7,  3])

In [206]:
b[0,::2,-1]

array([ 3, 11])

In [207]:
b[::-1]

array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [208]:
# flatten numpy 
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [209]:
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [210]:
b.shape = (6,4)

In [211]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [212]:
b.transpose()

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [213]:
b.resize(2,12)

In [214]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [215]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [216]:
a.shape

(3, 3)

In [217]:
b = 2 * a
b

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [218]:
np.hstack(
    (a,b)
)

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [219]:
np.concatenate((a,b),axis=1)

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [220]:
np.column_stack((a,b))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [221]:
np.vstack(
    (a,b)
)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [222]:
np.concatenate((a,b),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [223]:
np.row_stack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [224]:
np.dstack(
    (a,b)
)

array([[[ 0,  0],
        [ 1,  2],
        [ 2,  4]],

       [[ 3,  6],
        [ 4,  8],
        [ 5, 10]],

       [[ 6, 12],
        [ 7, 14],
        [ 8, 16]]])

In [225]:
np.dstack(
    (a,b)
).shape

(3, 3, 2)

In [226]:
oned = np.arange(2)
twice_oned = 2 * oned

In [227]:
print(oned)
print(twice_oned)

[0 1]
[0 2]


In [228]:
np.column_stack(
    (oned,twice_oned)
)

array([[0, 0],
       [1, 2]])

In [229]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [230]:
np.hsplit(a,3)

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

In [231]:
np.split(a,3,axis=1)

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

In [232]:
np.vsplit(a,3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [233]:
np.split(a,3,axis=0)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [234]:
c = np.arange(27).reshape(3,3,3)

In [235]:
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [236]:
np.dsplit(c,3)

[array([[[ 0],
         [ 3],
         [ 6]],
 
        [[ 9],
         [12],
         [15]],
 
        [[18],
         [21],
         [24]]]), array([[[ 1],
         [ 4],
         [ 7]],
 
        [[10],
         [13],
         [16]],
 
        [[19],
         [22],
         [25]]]), array([[[ 2],
         [ 5],
         [ 8]],
 
        [[11],
         [14],
         [17]],
 
        [[20],
         [23],
         [26]]])]

In [237]:
c.ndim # no. of dimension

3

In [238]:
c.size  # no. of items/elements

27

In [239]:
c.itemsize # no. of bytes of each element in array

8

In [240]:
c.nbytes  # total no. of bytes array require

216

In [241]:
c.size * c.itemsize

216

In [242]:
b = np.arange(24).reshape(2,12)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [243]:
b.resize(6,4)

In [244]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [245]:
b.T

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [246]:
# b.transpose()

In [247]:
b.ndim

2

In [248]:
np.split(b,1)[0][0]

array([0, 1, 2, 3])

# array from csv 

np.genfromtxt(csv,delimiter=',')

a , 2-d array

a[row,column]

In [249]:
# identity matrix
np.eye(2)

array([[1., 0.],
       [0., 1.]])

np.savetxt('_.txt',variables)

In [250]:
data = np.genfromtxt('data.csv',delimiter=',')

In [251]:
c,v = np.loadtxt('data.csv',delimiter=',',usecols=(6,7),unpack=True)

In [252]:
c # close price

array([336.1 , 339.32, 345.03, 344.32, 343.44, 346.5 , 351.88, 355.2 ,
       358.16, 354.54, 356.85, 359.18, 359.9 , 363.13, 358.3 , 350.56,
       338.61, 342.62, 342.88, 348.16, 353.21, 349.31, 352.12, 359.56,
       360.  , 355.36, 355.76, 352.47, 346.67, 351.99])

In [253]:
v # volume 

array([21144800., 13473000., 15236800.,  9242600., 14064100., 11494200.,
       17322100., 13608500., 17240800., 33162400., 13127500., 11086200.,
       10149000., 17184100., 18949000., 29144500., 31162200., 23994700.,
       17853500., 13572000., 14395400., 16290300., 21521000., 17885200.,
       16188000., 19504300., 12718000., 16192700., 18138800., 16824200.])

### Volume Weighted Average Price

* Quantity in finance
* Average price for a financial asset 
* Higher Volume. the more significant 

In [254]:
vwap = np.average(c,weights=v)
f'VWAP = {vwap}'

'VWAP = 350.5895493532009'

* arithmetic mean 

<center>$\large \frac{1}{n} \sum_{i=1}^na_i$</center>

In [255]:
vwap_mean = np.mean(c)
f'VWAP Mean = {vwap_mean}'

'VWAP Mean = 351.0376666666667'

### Time Weighted Average Price

* Another average price measure 


In [256]:
t = np.arange(len(c))
twap = np.average(c,weights=t)

f'TWAP Mean = {twap}'

'TWAP Mean = 352.4283218390804'

In [257]:
o_ = data[:,-3]

In [258]:
o_two = np.loadtxt('data.csv',delimiter=',',usecols=5,unpack=True)

In [259]:
sum(np.equal(o_,o_two))

30

In [260]:
h,l = np.loadtxt('data.csv',delimiter=",",usecols=(4,5),unpack=True)

In [261]:
print(f"Highest = {np.max(h)}\nLowest = {np.min(l)}")

Highest = 364.9
Lowest = 333.53


np.ptp(<col>) # difference between the maximum and minimum
values of an array.

In [262]:
print(np.ptp(h))
print(np.max(h)-np.min(h))

24.859999999999957
24.859999999999957


In [263]:
np.ptp(l)

26.970000000000027

In [264]:
(np.max(h) - np.min(l))/2

15.685000000000002

In [265]:
np.genfromtxt('data.csv',delimiter=',')[:,3:]

array([[3.44170e+02, 3.44400e+02, 3.33530e+02, 3.36100e+02, 2.11448e+07],
       [3.35800e+02, 3.40040e+02, 3.34300e+02, 3.39320e+02, 1.34730e+07],
       [3.41300e+02, 3.45650e+02, 3.40980e+02, 3.45030e+02, 1.52368e+07],
       [3.44450e+02, 3.45250e+02, 3.43550e+02, 3.44320e+02, 9.24260e+06],
       [3.43800e+02, 3.44240e+02, 3.38550e+02, 3.43440e+02, 1.40641e+07],
       [3.43610e+02, 3.46700e+02, 3.43510e+02, 3.46500e+02, 1.14942e+07],
       [3.47890e+02, 3.53250e+02, 3.47640e+02, 3.51880e+02, 1.73221e+07],
       [3.53680e+02, 3.55520e+02, 3.52150e+02, 3.55200e+02, 1.36085e+07],
       [3.55190e+02, 3.59000e+02, 3.54870e+02, 3.58160e+02, 1.72408e+07],
       [3.57390e+02, 3.60000e+02, 3.48000e+02, 3.54540e+02, 3.31624e+07],
       [3.54750e+02, 3.57800e+02, 3.53540e+02, 3.56850e+02, 1.31275e+07],
       [3.56790e+02, 3.59480e+02, 3.56710e+02, 3.59180e+02, 1.10862e+07],
       [3.59190e+02, 3.59970e+02, 3.57550e+02, 3.59900e+02, 1.01490e+07],
       [3.60800e+02, 3.64900e+02, 3.60

The arithmetic mean and weighted average are ways to find the center
of a distribution of values. However, neither are robust and both are sensitive to outliers.
Outliers are extreme values that are much bigger or smaller than the typical values in a
dataset. Usually, outliers are caused by a rare phenomenon or a measurement error.

In [266]:
c = np.loadtxt('data.csv',delimiter=',',usecols=(6,),unpack=True)

In [267]:
np.loadtxt('data.csv',delimiter=',',usecols=(6,))

array([336.1 , 339.32, 345.03, 344.32, 343.44, 346.5 , 351.88, 355.2 ,
       358.16, 354.54, 356.85, 359.18, 359.9 , 363.13, 358.3 , 350.56,
       338.61, 342.62, 342.88, 348.16, 353.21, 349.31, 352.12, 359.56,
       360.  , 355.36, 355.76, 352.47, 346.67, 351.99])

In [268]:
np.loadtxt('data.csv',delimiter=',',usecols=(6,),unpack=True)

array([336.1 , 339.32, 345.03, 344.32, 343.44, 346.5 , 351.88, 355.2 ,
       358.16, 354.54, 356.85, 359.18, 359.9 , 363.13, 358.3 , 350.56,
       338.61, 342.62, 342.88, 348.16, 353.21, 349.31, 352.12, 359.56,
       360.  , 355.36, 355.76, 352.47, 346.67, 351.99])

In [269]:
np.genfromtxt('data.csv',delimiter=',')

array([[        nan,         nan,         nan, 3.44170e+02, 3.44400e+02,
        3.33530e+02, 3.36100e+02, 2.11448e+07],
       [        nan,         nan,         nan, 3.35800e+02, 3.40040e+02,
        3.34300e+02, 3.39320e+02, 1.34730e+07],
       [        nan,         nan,         nan, 3.41300e+02, 3.45650e+02,
        3.40980e+02, 3.45030e+02, 1.52368e+07],
       [        nan,         nan,         nan, 3.44450e+02, 3.45250e+02,
        3.43550e+02, 3.44320e+02, 9.24260e+06],
       [        nan,         nan,         nan, 3.43800e+02, 3.44240e+02,
        3.38550e+02, 3.43440e+02, 1.40641e+07],
       [        nan,         nan,         nan, 3.43610e+02, 3.46700e+02,
        3.43510e+02, 3.46500e+02, 1.14942e+07],
       [        nan,         nan,         nan, 3.47890e+02, 3.53250e+02,
        3.47640e+02, 3.51880e+02, 1.73221e+07],
       [        nan,         nan,         nan, 3.53680e+02, 3.55520e+02,
        3.52150e+02, 3.55200e+02, 1.36085e+07],
       [        nan,         nan

In [270]:
c

array([336.1 , 339.32, 345.03, 344.32, 343.44, 346.5 , 351.88, 355.2 ,
       358.16, 354.54, 356.85, 359.18, 359.9 , 363.13, 358.3 , 350.56,
       338.61, 342.62, 342.88, 348.16, 353.21, 349.31, 352.12, 359.56,
       360.  , 355.36, 355.76, 352.47, 346.67, 351.99])

In [271]:
sorted_close = np.msort(c)

In [272]:
N = len(sorted_close)

In [273]:
sorted_close[int((N-1)/2)]

351.99

In [274]:
sorted_close[int((N)/2)]

352.12

In [275]:
np.median(sorted_close)

352.055

Stock Return

Simple returns are just the rate of change from one value to the next.<br>
Logarithmic returns, or log returns, are determined by taking the log of all the prices and
calculating the differences between them. <br>

Anyway, investors
are most likely to be interested in the variance or standard deviation of the returns, as this
represents risk.

$log(a) - log(b) = log\frac{a}{b}$

In [276]:
first_arr = np.array([1,2,3,5])
first_arr

array([1, 2, 3, 5])

In [277]:
new_first_arr = np.insert(first_arr,3,4)
new_first_arr

array([1, 2, 3, 4, 5])

In [278]:
second_arr = np.array([1,2,3,4])
second_arr

array([1, 2, 3, 4])

In [279]:
new_second_arr = np.append(second_arr,5)
new_second_arr

array([1, 2, 3, 4, 5])

In [280]:
third_app = np.array([1,2,3,4,5])
del_arr = np.delete(third_app,4)
del_arr

array([1, 2, 3, 4])

In [281]:
first_arr = np.arange(1,13)
first_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [282]:
np.reshape(first_arr,(3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [283]:
np.reshape(first_arr,(3,2,2))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [284]:
np.reshape(np.arange(12),(3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [285]:
np.reshape(np.arange(3*4*5),(3,4,5))

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [287]:
arr1 = np.array([2,4,6,8,10])
arr2 = np.array([1,3,5,7,9])

arr3 = np.concatenate((arr1, arr2), axis=0)
arr3.shape

(10,)

In [288]:
a=np.arange(1,10).reshape(3,3) # 3 x 3
b=np.arange(1,4) # 1 x 3

In [289]:
a+b

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [294]:
b + a

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [295]:
d = np.arange(24).reshape(2,3,4)
d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [296]:
e = np.arange(4)

In [297]:
d - e

array([[[ 0,  0,  0,  0],
        [ 4,  4,  4,  4],
        [ 8,  8,  8,  8]],

       [[12, 12, 12, 12],
        [16, 16, 16, 16],
        [20, 20, 20, 20]]])

In [304]:
first_arr = np.arange(10,110,10)
second_arr = np.arange(10,100,10).reshape(3,3)
third_arr = np.arange(10,110,10).reshape(2,5)

In [299]:
second_arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [300]:
third_app

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [301]:
first_arr.sum()

550

In [302]:
second_arr.sum()

450

In [305]:
third_arr.sum()

550

In [307]:
first_2dimarr = np.arange(12).reshape((3,4))

In [308]:
first_2dimarr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [309]:
np.transpose(first_2dimarr)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [310]:
second_2dimarr = np.arange(6).reshape(3,2)
second_2dimarr

array([[0, 1],
       [2, 3],
       [4, 5]])

In [312]:
np.transpose(second_2dimarr,(1,0))

array([[0, 2, 4],
       [1, 3, 5]])

In [313]:
np.transpose(second_2dimarr)

array([[0, 2, 4],
       [1, 3, 5]])

In [314]:
import numpy as np

In [315]:
first_2dimarr = np.arange(12).reshape(3,4)
first_2dimarr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [316]:
np.transpose(first_2dimarr)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [317]:
second_2dimarr = np.arange(6).reshape(3,2)
second_2dimarr

array([[0, 1],
       [2, 3],
       [4, 5]])

In [319]:
np.transpose(second_2dimarr,(1,0))

array([[0, 2, 4],
       [1, 3, 5]])

In [320]:
np.transpose(second_2dimarr)

array([[0, 2, 4],
       [1, 3, 5]])

In [321]:
firs_3dimarr=np.arange(24).reshape(2,3,4)
firs_3dimarr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [322]:
np.moveaxis(firs_3dimarr,0,-1)

array([[[ 0, 12],
        [ 1, 13],
        [ 2, 14],
        [ 3, 15]],

       [[ 4, 16],
        [ 5, 17],
        [ 6, 18],
        [ 7, 19]],

       [[ 8, 20],
        [ 9, 21],
        [10, 22],
        [11, 23]]])