In [1]:
import numpy as np

In [2]:
a = np.arange(5)

In [3]:
a

array([0, 1, 2, 3, 4])

In [4]:
a.dtype

dtype('int32')

In [5]:
a.shape

(5,)

In [6]:
m = np.array([np.arange(2),np.arange(2)])
m

array([[0, 1],
       [0, 1]])

In [7]:
m.shape

(2, 2)

In [8]:
n = np.array([
    np.arange(3),
    np.arange(3),
    np.arange(3)
])

n

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [9]:
n.shape

(3, 3)

In [10]:
a = np.array([
    [1,2],
    [3,4]
])

a

array([[1, 2],
       [3, 4]])

In [11]:
print(a[0,0])
print(a[0,1])
print(a[1,0])
print(a[1,1])

1
2
3
4


> $ i \space  \text{is the square root of} -1 $

e.g.  $2.5 + 3.7i$

In [12]:
np.arange(7,dtype='uint16')

array([0, 1, 2, 3, 4, 5, 6], dtype=uint16)

In [13]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [14]:
a

array([[1, 2],
       [3, 4]])

In [15]:
a.dtype.itemsize

4

In [16]:
np.arange(7,dtype='i') # integer

array([0, 1, 2, 3, 4, 5, 6], dtype=int32)

In [17]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
a[3:7]

array([3, 4, 5, 6])

In [19]:
a[:7:2]

array([0, 2, 4, 6])

In [20]:
a[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1, 0])

In [21]:
b = np.arange(24)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [22]:
b = b.reshape(2,3,4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [23]:
b.shape

(2, 3, 4)

In [24]:
b[0,0,0]

0

In [25]:
b[:,0,0]

array([ 0, 12])

In [26]:
b[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
b[0,:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
b[0,...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
b[0,1]

array([4, 5, 6, 7])

In [30]:
b[0,1,::2]

array([4, 6])

In [31]:
b[...,1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [32]:
b[:,1]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [33]:
b[0,:,1]

array([1, 5, 9])

In [34]:
b[0,:,-1]

array([ 3,  7, 11])

In [35]:
b[0,::-1,-1]

array([11,  7,  3])

In [36]:
b[0,::2,-1]

array([ 3, 11])

In [37]:
b[::-1]

array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [38]:
# flatten numpy 
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [39]:
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [40]:
b.shape = (6,4)

In [41]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [42]:
b.transpose()

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [43]:
b.resize(2,12)

In [44]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [45]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [46]:
a.shape

(3, 3)

In [47]:
b = 2 * a
b

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [48]:
np.hstack(
    (a,b)
)

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [49]:
np.concatenate((a,b),axis=1)

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [50]:
np.column_stack((a,b))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [51]:
np.vstack(
    (a,b)
)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [52]:
np.concatenate((a,b),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [53]:
np.row_stack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [54]:
np.dstack(
    (a,b)
)

array([[[ 0,  0],
        [ 1,  2],
        [ 2,  4]],

       [[ 3,  6],
        [ 4,  8],
        [ 5, 10]],

       [[ 6, 12],
        [ 7, 14],
        [ 8, 16]]])

In [55]:
np.dstack(
    (a,b)
).shape

(3, 3, 2)

In [56]:
oned = np.arange(2)
twice_oned = 2 * oned

In [57]:
print(oned)
print(twice_oned)

[0 1]
[0 2]


In [58]:
np.column_stack(
    (oned,twice_oned)
)

array([[0, 0],
       [1, 2]])

In [59]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [60]:
np.hsplit(a,3)

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

In [61]:
np.split(a,3,axis=1)

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

In [62]:
np.vsplit(a,3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [63]:
np.split(a,3,axis=0)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [64]:
c = np.arange(27).reshape(3,3,3)

In [65]:
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [66]:
np.dsplit(c,3)

[array([[[ 0],
         [ 3],
         [ 6]],
 
        [[ 9],
         [12],
         [15]],
 
        [[18],
         [21],
         [24]]]), array([[[ 1],
         [ 4],
         [ 7]],
 
        [[10],
         [13],
         [16]],
 
        [[19],
         [22],
         [25]]]), array([[[ 2],
         [ 5],
         [ 8]],
 
        [[11],
         [14],
         [17]],
 
        [[20],
         [23],
         [26]]])]

In [67]:
c.ndim # no. of dimension

3

In [68]:
c.size  # no. of items/elements

27

In [69]:
c.itemsize # no. of bytes of each element in array

4

In [70]:
c.nbytes  # total no. of bytes array require

108

In [71]:
c.size * c.itemsize

108

In [72]:
b = np.arange(24).reshape(2,12)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [73]:
b.resize(6,4)

In [74]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [75]:
b.T

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [76]:
# b.transpose()

In [77]:
b.ndim

2

In [78]:
np.split(b,1)[0][0]

array([0, 1, 2, 3])

# array from csv 

np.genfromtxt(csv,delimiter=',')

a , 2-d array

a[row,column]

In [79]:
# identity matrix
np.eye(2)

array([[1., 0.],
       [0., 1.]])

np.savetxt('_.txt',variables)

In [80]:
data = np.genfromtxt('data.csv',delimiter=',')

In [81]:
c,v = np.loadtxt('data.csv',delimiter=',',usecols=(6,7),unpack=True)

In [82]:
c # close price

array([336.1 , 339.32, 345.03, 344.32, 343.44, 346.5 , 351.88, 355.2 ,
       358.16, 354.54, 356.85, 359.18, 359.9 , 363.13, 358.3 , 350.56,
       338.61, 342.62, 342.88, 348.16, 353.21, 349.31, 352.12, 359.56,
       360.  , 355.36, 355.76, 352.47, 346.67, 351.99])

In [83]:
v # volume 

array([21144800., 13473000., 15236800.,  9242600., 14064100., 11494200.,
       17322100., 13608500., 17240800., 33162400., 13127500., 11086200.,
       10149000., 17184100., 18949000., 29144500., 31162200., 23994700.,
       17853500., 13572000., 14395400., 16290300., 21521000., 17885200.,
       16188000., 19504300., 12718000., 16192700., 18138800., 16824200.])

### Volume Weighted Average Price

* Quantity in finance
* Average price for a financial asset 
* Higher Volume. the more significant 

In [84]:
vwap = np.average(c,weights=v)
f'VWAP = {vwap}'

'VWAP = 350.5895493532009'

* arithmetic mean 

<center>$\large \frac{1}{n} \sum_{i=1}^na_i$</center>

In [85]:
vwap_mean = np.mean(c)
f'VWAP Mean = {vwap_mean}'

'VWAP Mean = 351.0376666666667'

### Time Weighted Average Price

* Another average price measure 


In [86]:
t = np.arange(len(c))
twap = np.average(c,weights=t)

f'TWAP Mean = {twap}'

'TWAP Mean = 352.4283218390804'

In [87]:
o_ = data[:,-3]

In [88]:
o_two = np.loadtxt('data.csv',delimiter=',',usecols=5,unpack=True)

In [90]:
sum(np.equal(o_,o_two))

30

In [91]:
h,l = np.loadtxt('data.csv',delimiter=",",usecols=(4,5),unpack=True)

In [92]:
print(f"Highest = {np.max(h)}\nLowest = {np.min(l)}")

Highest = 364.9
Lowest = 333.53


np.ptp(<col>) # difference between the maximum and minimum
values of an array.

In [95]:
print(np.ptp(h))
print(np.max(h)-np.min(h))

24.859999999999957
24.859999999999957


In [94]:
np.ptp(l)

26.970000000000027

In [114]:
(np.max(h) - np.min(l))/2

15.685000000000002

In [113]:
np.genfromtxt('data.csv',delimiter=',')[:,3:]

array([[3.44170e+02, 3.44400e+02, 3.33530e+02, 3.36100e+02, 2.11448e+07],
       [3.35800e+02, 3.40040e+02, 3.34300e+02, 3.39320e+02, 1.34730e+07],
       [3.41300e+02, 3.45650e+02, 3.40980e+02, 3.45030e+02, 1.52368e+07],
       [3.44450e+02, 3.45250e+02, 3.43550e+02, 3.44320e+02, 9.24260e+06],
       [3.43800e+02, 3.44240e+02, 3.38550e+02, 3.43440e+02, 1.40641e+07],
       [3.43610e+02, 3.46700e+02, 3.43510e+02, 3.46500e+02, 1.14942e+07],
       [3.47890e+02, 3.53250e+02, 3.47640e+02, 3.51880e+02, 1.73221e+07],
       [3.53680e+02, 3.55520e+02, 3.52150e+02, 3.55200e+02, 1.36085e+07],
       [3.55190e+02, 3.59000e+02, 3.54870e+02, 3.58160e+02, 1.72408e+07],
       [3.57390e+02, 3.60000e+02, 3.48000e+02, 3.54540e+02, 3.31624e+07],
       [3.54750e+02, 3.57800e+02, 3.53540e+02, 3.56850e+02, 1.31275e+07],
       [3.56790e+02, 3.59480e+02, 3.56710e+02, 3.59180e+02, 1.10862e+07],
       [3.59190e+02, 3.59970e+02, 3.57550e+02, 3.59900e+02, 1.01490e+07],
       [3.60800e+02, 3.64900e+02, 3.60

The arithmetic mean and weighted average are ways to find the center
of a distribution of values. However, neither are robust and both are sensitive to outliers.
Outliers are extreme values that are much bigger or smaller than the typical values in a
dataset. Usually, outliers are caused by a rare phenomenon or a measurement error.

In [117]:
c = np.loadtxt('data.csv',delimiter=',',usecols=(6,),unpack=True)

In [119]:
np.loadtxt('data.csv',delimiter=',',usecols=(6,))

array([336.1 , 339.32, 345.03, 344.32, 343.44, 346.5 , 351.88, 355.2 ,
       358.16, 354.54, 356.85, 359.18, 359.9 , 363.13, 358.3 , 350.56,
       338.61, 342.62, 342.88, 348.16, 353.21, 349.31, 352.12, 359.56,
       360.  , 355.36, 355.76, 352.47, 346.67, 351.99])

In [121]:
np.loadtxt('data.csv',delimiter=',',usecols=(6,),unpack=True)

array([336.1 , 339.32, 345.03, 344.32, 343.44, 346.5 , 351.88, 355.2 ,
       358.16, 354.54, 356.85, 359.18, 359.9 , 363.13, 358.3 , 350.56,
       338.61, 342.62, 342.88, 348.16, 353.21, 349.31, 352.12, 359.56,
       360.  , 355.36, 355.76, 352.47, 346.67, 351.99])

In [123]:
np.genfromtxt('data.csv',delimiter=',')

array([[        nan,         nan,         nan, 3.44170e+02, 3.44400e+02,
        3.33530e+02, 3.36100e+02, 2.11448e+07],
       [        nan,         nan,         nan, 3.35800e+02, 3.40040e+02,
        3.34300e+02, 3.39320e+02, 1.34730e+07],
       [        nan,         nan,         nan, 3.41300e+02, 3.45650e+02,
        3.40980e+02, 3.45030e+02, 1.52368e+07],
       [        nan,         nan,         nan, 3.44450e+02, 3.45250e+02,
        3.43550e+02, 3.44320e+02, 9.24260e+06],
       [        nan,         nan,         nan, 3.43800e+02, 3.44240e+02,
        3.38550e+02, 3.43440e+02, 1.40641e+07],
       [        nan,         nan,         nan, 3.43610e+02, 3.46700e+02,
        3.43510e+02, 3.46500e+02, 1.14942e+07],
       [        nan,         nan,         nan, 3.47890e+02, 3.53250e+02,
        3.47640e+02, 3.51880e+02, 1.73221e+07],
       [        nan,         nan,         nan, 3.53680e+02, 3.55520e+02,
        3.52150e+02, 3.55200e+02, 1.36085e+07],
       [        nan,         nan

In [124]:
c

array([336.1 , 339.32, 345.03, 344.32, 343.44, 346.5 , 351.88, 355.2 ,
       358.16, 354.54, 356.85, 359.18, 359.9 , 363.13, 358.3 , 350.56,
       338.61, 342.62, 342.88, 348.16, 353.21, 349.31, 352.12, 359.56,
       360.  , 355.36, 355.76, 352.47, 346.67, 351.99])

In [129]:
sorted_close = np.msort(c)

In [130]:
N = len(sorted_close)

In [136]:
sorted_close[int((N-1)/2)]

351.99

In [134]:
sorted_close[int((N)/2)]

352.12

In [135]:
np.median(sorted_close)

352.055

Stock Return

Simple returns are just the rate of change from one value to the next.<br>
Logarithmic returns, or log returns, are determined by taking the log of all the prices and
calculating the differences between them. <br>

Anyway, investors
are most likely to be interested in the variance or standard deviation of the returns, as this
represents risk.

$log(a) - log(b) = log\frac{a}{b}$